/**
 * The syllabus, as data.
 *
 * Kept in one place so the markup stays readable and so the parser can never
 * drift from what is displayed. Counts per chapter are asserted in script.js
 * against the totals recorded in DSA_Problems.txt.
 */

const CURRICULUM = [
    {
        slug: 'basics',
        title: 'Basics',
        blurb: 'What every other chapter assumes you already know.',
        problems: [
            'Big O notation, order of growth, analysis of common loops',
        ],
    },
    {
        slug: 'basic-programs',
        title: 'Basics Programs',
        blurb: 'The small warm-up set. Write each one without thinking twice.',
        problems: [
            'Sum of natural numbers',
            'Count digits',
            'Palindrome number',
            'Factorial of a number',
            'GCD or HCF of two numbers',
            'LCM of two numbers',
            'Check for prime',
            'Prime factorization',
            'All divisors of a number',
            'Sieve of Eratosthenes',
            'Computing power',
            'Iterative power (binary exponentiation)',
        ],
    },
    {
        slug: 'bitwise',
        title: 'Bitwise',
        blurb: 'Seven problems that make the rest of the course cheaper.',
        problems: [
            'Check kth bit is set or not',
            'Count set bits',
            'Find the only odd one',
            'Power of 2',
            'One odd occurring',
            'Two odd occurring',
            'Power set using bitwise',
        ],
    },
    {
        slug: 'recursion',
        title: 'Recursion',
        blurb: 'Where iteration stops being the obvious answer.',
        problems: [
            'Print 1 to N',
            'Print N to 1',
            'Tail recursion',
            'Writing base cases in recursion',
            'Sum of digits',
            'Palindrome check',
            'Rope cutting problem',
            'Tower of Hanoi',
            'Josephus problem',
            'Find all distinct subset (or subsequence) sums',
            'Print all permutations',
            'Restrictive candy crush',
        ],
    },
    {
        slug: 'lists',
        title: 'Lists',
        blurb: 'Two pointers, prefix sums and sliding windows: the list toolkit.',
        problems: [
            'Average or mean of a list',
            'Separate even or odd',
            'Get smaller elements',
            'Largest element in list',
            'Second largest element in list',
            'Check if list is sorted',
            'Reverse a list',
            'Remove duplicates',
            'Happiest triplet',
            'Left rotate a list by one',
            'Left rotate a list by d places',
            'Maximum subarray sum',
            'Longest even odd subarray',
            'Maximum circular sum subarray',
            'Majority element',
            'Min number of flips',
            'Sliding window technique',
            'Subarray with given sum',
            'Prefix sum technique',
            'Equilibrium point',
            'Maximum appearing element in ranges',
        ],
    },
    {
        slug: 'searching',
        title: 'Searching',
        blurb: 'Binary search and the shapes that break it.',
        problems: [
            'Binary search',
            'Recursive binary search',
            'Analysis of binary search',
            'Index of first occurrence in a sorted array',
            'Index of last occurrence',
            'Count 1s in a sorted array',
            'Square root',
            'Sorted array search',
            'Search in rotated array',
            'Find kth rotation',
            'Count occurrence in a sorted array',
            'Two pointers approach',
            'Triplet in a sorted array',
            'Median of two sorted arrays',
            'Repeating element',
            'Allocate minimum pages (naive method)',
            'Allocate minimum pages (binary search)',
        ],
    },
    {
        slug: 'sorting',
        title: 'Sorting',
        blurb: 'The largest chapter, and the one that pays off the most.',
        problems: [
            'Bubble sort',
            'Selection sort',
            'Insertion sort',
            'Merge sort',
            'Merge two sorted arrays',
            'Merge sort (overlapping ranges)',
            'Union of two sorted arrays',
            'Intersection of two sorted arrays',
            'Count inversions in arrays',
            'Partition a given array',
            "Hoare's partition",
            'Quick sort',
            'Quick sort using Lomuto partition',
            "Quick sort using Hoare's partition",
            'Heap sort',
            'Kth smallest',
            'Minimum difference in an array',
            'Chocolate distribution problem',
            'Sort an array with two types of elements',
            'Sort an array with three types of elements',
            'Merge overlapping',
            'Meeting the maximum guests',
            'Counting sort',
            'Cyclic sort',
            'Radix sort',
            'Bucket sort',
        ],
    },
    {
        slug: 'matrix',
        title: 'Matrix',
        blurb: 'Traversal patterns and 2D binary search.',
        problems: [
            'N-D arrays',
            'Passing a 2D array as an argument',
            'Matrix in snake pattern',
            'Matrix boundary traversal',
            'Transpose of a matrix',
            'Row with max 1s',
            'Median of row-wise sorted matrix',
            'Median in a row-wise sorted matrix',
        ],
    },
    {
        slug: 'hashing',
        title: 'Hashing',
        blurb: 'Trade memory for time. Then do it twenty more times.',
        problems: [
            'Direct address table',
            'Hashing functions',
            'Collision handling',
            'Chaining',
            'Open addressing',
            'Double hashing',
            'Frequencies in a limited array',
            'Set in Python',
            'Sort an array with two types of elements',
            'Count distinct elements in a list',
            'Intersection of two arrays',
            'Distinct substrings',
            'Subarray with given sum',
            'Check for palindrome permutations',
            'Longest subarray with given sum',
            'Longest subarray with equal number of zero and one',
            'Longest common span with same sum in binary array',
            'Count distinct element in every window',
            'More than n/k occurrence',
            'Count subarray with k odds',
        ],
    },
    {
        slug: 'strings',
        title: 'Strings',
        blurb: 'Pattern matching, and the proofs behind KMP and Rabin-Karp.',
        problems: [
            'Escape sequences and raw strings',
            'Formatted strings in Python',
            'String comparisons',
            'Reverse a string',
            'Validate an IP address',
            'Check for palindrome',
            'Check if a string is a subsequence of another',
            'Check for anagram',
            'Leftmost repeating character',
            'Reverse words in a string',
            'Pattern searching in a string',
            'Naive pattern searching',
            'Naive pattern searching for distinct',
            'Rabin-Karp',
            'KMP algorithm',
            'Lexicographic rank of a string',
            'Longest substring with distinct characters',
            'Multiply two strings',
            'String subsequence',
        ],
    },
];

/** Flattened search index, built once at load. */
const SEARCH_INDEX = CURRICULUM.flatMap((chapter) =>
    chapter.problems.map((name, i) => ({
        chapterSlug: chapter.slug,
        chapterTitle: chapter.title,
        name,
        ordinal: i + 1,
    }))
);

// Top-level `const` in a classic script is NOT a window property, so hand the
// data over explicitly. `module` covers the same file under Node for tests.
if (typeof window !== 'undefined') {
    window.CURRICULUM = CURRICULUM;
    window.SEARCH_INDEX = SEARCH_INDEX;
}

if (typeof module !== 'undefined') {
    module.exports = { CURRICULUM, SEARCH_INDEX };
}
